=== Ararat3010/TI-PMP2/TechnischeInformatikRepository/Technische Informatik Semester 2/Aufgabenblatt1/Raspberry.dtd
<!ELEMENT Raspberry (name+, ip+, sensoren*)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT ip (#PCDATA)>

<!ELEMENT sensoren (ort?, typ?, wert?)>
<!ELEMENT ort (#PCDATA)>
<!ELEMENT typ (#PCDATA)>
<!ELEMENT wert (#PCDATA)>

=== Ararat3010/TI-PMP2/TechnischeInformatikRepository/Technische Informatik Semester 2/src/Aufgabenblatt1/Raspberry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Raspberry SYSTEM "src/Aufgabenblatt1/Raspberry.dtd">
<Raspberry>
	<name>Raspberry</name>
	<ip>192.168.2.1</ip>
	<sensoren>
		<ort>Wohnzimmer</ort>
		<typ>Temperatur</typ>
		<wert>22.4</wert>
	</sensoren>
	<sensoren>
		<ort>KÃ¼che</ort>
		<wert>-1.2323</wert>
	</sensoren>
	<sensoren>
		<ort>Badezimmer</ort>
		<typ>Luftfeuchtigkeit</typ>
		<wert>63.8</wert>
	</sensoren>
</Raspberry>
